"""add provider metadata to messages

Revision ID: 714252c64773
Revises: 8e899474af46
Create Date: 2026-07-10 22:27:58.152411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714252c64773'
down_revision: Union[str, Sequence[str], None] = '8e899474af46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('latency', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    op.drop_column('messages', 'token_count')
    op.drop_column('messages', 'latency')
    op.drop_column('messages', 'provider')
    # ### end Alembic commands ###
