"""add ui preferences

Revision ID: 839abd3e4152
Revises: c2773335d59e
Create Date: 2026-07-12 22:41:19.380135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839abd3e4152'
down_revision: Union[str, Sequence[str], None] = 'c2773335d59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_preferences',
        sa.Column(
            'render_markdown',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )
    op.add_column(
        'user_preferences',
        sa.Column(
            'code_highlighting',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )
    op.add_column(
        'user_preferences',
        sa.Column(
            'font_size',
            sa.Integer(),
            nullable=False,
            server_default='16'
        )
    )
    op.add_column(
        'user_preferences',
        sa.Column(
            'compact_mode',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    op.add_column(
        'user_preferences',
        sa.Column(
            'sidebar_collapsed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'sidebar_collapsed')
    op.drop_column('user_preferences', 'compact_mode')
    op.drop_column('user_preferences', 'font_size')
    op.drop_column('user_preferences', 'code_highlighting')
    op.drop_column('user_preferences', 'render_markdown')
    # ### end Alembic commands ###
