"""rename preference columns

Revision ID: 8e899474af46
Revises: 15525223434f
Create Date: 2026-06-03 10:51:49.417547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e899474af46'
down_revision: Union[str, Sequence[str], None] = '15525223434f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('preferred_provider', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('preferred_model', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('preferred_style', sa.String(), nullable=True))
    op.drop_column('user_preferences', 'preffered_provider')
    op.drop_column('user_preferences', 'preffered_model')
    op.drop_column('user_preferences', 'preffered_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('preffered_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('preffered_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('preffered_provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_preferences', 'preferred_style')
    op.drop_column('user_preferences', 'preferred_model')
    op.drop_column('user_preferences', 'preferred_provider')
    # ### end Alembic commands ###
