"""create chat sessions and messages

Revision ID: 96f118cd8e3e
Revises: a1dd2bcf2350
Create Date: 2026-05-29 12:09:54.131894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f118cd8e3e'
down_revision: Union[str, Sequence[str], None] = 'a1dd2bcf2350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
